import { app, BrowserWindow } from 'electron';
import { spawn } from 'child_process';

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
	// eslint-disable-line global-require
	app.quit();
}

const createWindow = (): void => {

	startDjangoServer();

	// Create the browser window.
	const mainWindow = new BrowserWindow({
	height: 600,
	width: 800,
	});

	mainWindow.webContents.session.webRequest.onBeforeSendHeaders(
	(details, callback) => {
		const { requestHeaders } = details;
		UpsertKeyValue(requestHeaders, 'Access-Control-Allow-Origin', ['*']);
		callback({ requestHeaders });
	},
	);

	mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
		const { responseHeaders } = details;
		UpsertKeyValue(responseHeaders, 'Access-Control-Allow-Origin', ['*']);
		UpsertKeyValue(responseHeaders, 'Access-Control-Allow-Headers', ['*']);
		callback({
			responseHeaders,
		});
	});

	// and load the index.html of the app.
	mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

	// Open the DevTools.
	mainWindow.webContents.openDevTools();
};

const UpsertKeyValue = (obj : any, keyToChange : string, value : string[]) => {
	const keyToChangeLower = keyToChange.toLowerCase();
	for (const key of Object.keys(obj)) {
		if (key.toLowerCase() === keyToChangeLower) {
		// Reassign old key
		obj[key] = value;
		// Done
		return;
		}
	}
	// Insert at end instead
	obj[keyToChange] = value;
	}

const startDjangoServer = () =>
{
	const djangoBackend = spawn(`python\\edtwExampleEnv\\Scripts\\python.exe`,
		['python\\edtwExample\\manage.py', 'runserver', '--noreload']);
	djangoBackend.stdout.on('data', data =>
	{
		console.log(`stdout:\n${data}`);
	});
	djangoBackend.stderr.on('data', data =>
	{
		console.log(`stderr: ${data}`);
	});
	djangoBackend.on('error', (error) =>
	{
		console.log(`error: ${error.message}`);
	});
	djangoBackend.on('close', (code) =>
	{
		console.log(`child process exited with code ${code}`);
	});
	djangoBackend.on('message', (message) =>
	{
		console.log(`stdout:\n${message}`);
	});
	return djangoBackend;
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit();
	}
});

app.on('activate', () => {
	// On OS X it's common to re-create a window in the app when the
	// dock icon is clicked and there are no other windows open.
	if (BrowserWindow.getAllWindows().length === 0) {
	createWindow();
	}
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
