import { app, BrowserWindow } from 'electron';
import { spawn, ChildProcessWithoutNullStreams } from 'child_process';
import kill from 'tree-kill';

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
let DJANGO_CHILD_PROCESS: ChildProcessWithoutNullStreams = null;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
	// eslint-disable-line global-require
	app.quit();
}

const createWindow = (): void => {

	startDjangoServer();

	// Create the browser window.
	const mainWindow = new BrowserWindow({
		height: 600,
		width: 800,
	});

	mainWindow.webContents.session.webRequest.onBeforeSendHeaders(
	(details, callback) => {
		const { requestHeaders } = details;
		UpsertKeyValue(requestHeaders, 'Access-Control-Allow-Origin', ['*']);
		callback({ requestHeaders });
	},
	);

	mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
		const { responseHeaders } = details;
		UpsertKeyValue(responseHeaders, 'Access-Control-Allow-Origin', ['*']);
		UpsertKeyValue(responseHeaders, 'Access-Control-Allow-Headers', ['*']);
		callback({
			responseHeaders,
		});
	});

	// and load the index.html of the app.
	mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

	// Open the DevTools.
	openDevTools( mainWindow );
};

const UpsertKeyValue = (obj : any, keyToChange : string, value : string[]) => {
	const keyToChangeLower = keyToChange.toLowerCase();
	for (const key of Object.keys(obj)) {
		if (key.toLowerCase() === keyToChangeLower) {
		// Reassign old key
		obj[key] = value;
		// Done
		return;
		}
	}
	// Insert at end instead
	obj[keyToChange] = value;
	}

const startDjangoServer = () =>
{
	DJANGO_CHILD_PROCESS = spawnDjango();
	DJANGO_CHILD_PROCESS.stdout.on('data', data =>
	{
		console.log(`stdout:\n${data}`);
	});
	DJANGO_CHILD_PROCESS.stderr.on('data', data =>
	{
		console.log(`stderr: ${data}`);
	});
	DJANGO_CHILD_PROCESS.on('error', (error) =>
	{
		console.log(`error: ${error.message}`);
	});
	DJANGO_CHILD_PROCESS.on('close', (code) =>
	{
		console.log(`child process exited with code ${code}`);
	});
	DJANGO_CHILD_PROCESS.on('message', (message) =>
	{
		console.log(`stdout:\n${message}`);
	});
	return DJANGO_CHILD_PROCESS;
}

const spawnDjango = () =>
{
	if ( isDevelopmentEnv() )
	{
		return spawn(`python\\edtwExampleEnv\\Scripts\\python.exe`,
		['python\\edtwExample\\manage.py', 'runserver', '--noreload'], {
			shell: true,
		});
	}
	return spawn(`cd python && edtwExample.exe runserver --settings=edtwExample.settings.prod --noreload`,  {
		shell: true,
	});
}

const openDevTools = ( mainWindow : BrowserWindow ) => {

	if ( isDevelopmentEnv() )
	{
		mainWindow.webContents.openDevTools();
	}
}

const isDevelopmentEnv = () => {
	console.log( `NODE_ENV=${ process.env.NODE_ENV }` )
	return process.env.NODE_ENV == 'development'
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit();
	}
	kill( DJANGO_CHILD_PROCESS.pid );
});

app.on('before-quit', async function ()
{
	// Kill python process when the window is closed
	kill( DJANGO_CHILD_PROCESS.pid );
})

app.on('activate', () => {
	// On OS X it's common to re-create a window in the app when the
	// dock icon is clicked and there are no other windows open.
	if (BrowserWindow.getAllWindows().length === 0) {
		createWindow();
	}
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
